services:
  mongodb:
    image: jaganf8/mongodb:1.0.0
    container_name: mongodb
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db
    networks:
      - roboshop

  

  catalogue:
    image: jaganf8/catalogue:1.0.0
    container_name: catalogue
    environment:
      - MONGO=true
      - MONGO_URL=mongodb://mongodb:27017/catalogue
    ports:
      - "8080:8080"
    networks:
      - roboshop
  
volumes:
  mongo_data:
  redis_data:
  mysql_data:
  rabbitmq_data:

networks:
  roboshop:
    driver: bridge